version: "3.8"
services:
  mysqldb:
   image: mysql:latest
   restart: unless-stopped
 
   environment: 
    - MYSQL_USER=root
    - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    - MYSQL_DATABASE=testF
   ports:
    - 3306:3307
   volumes:
    - db:/var/lib/mysql
  app:
    depends_on:
     - mysqldb
    image: gestfcompose:latest
    build: ./
    restart: on-failure
   
    ports:
     - 8082:8083
    environment: 
     SPRING_APPLICATION_JSON: '{
      "spring.datasource.url" : "jdbc:mysql://mysqldb:3306/testF?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC",
      "spring.datasource.username":"root",
      "spring.datasource.password":"", 
      "spring.jpa.properties.hibernate.dialect": "org.hibernate.dialect.MySQL5InnoDBDialect",
      "spring.jpa.hibernate.ddl-auto": "update"
       }'
    volumes:
     - .m2:/root/.m2
    stdin_open: true
    tty: true
    
volumes:
 db: 
